# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
